[ -f ~/.ssh/id_ed25519 ] && ssh-add --apple-use-keychain ~/.ssh/id_ed25519 2>/dev/null

# oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh

# Aliases
alias termconf="code ~/.zshrc"
alias ohmyzsh="code ~/.oh-my-zsh"
alias glog2="git log --graph --pretty=tformat:'%Cred%h%Creset -%C(yellow)%d%Creset%s %Cgreen(%an %cr)%Creset' --abbrev-commit --date=relative --all"
# Link repo to local site
alias linkthemes='f() { ln -s ~/a8c/repos/themes ~/a8c/Local\ sites/$1/app/public/wp-content/themes/a8c-themes };f'
alias linkcom='f() { ln -s ~/a8c/repos/community ~/a8c/Local\ sites/$1/app/public/wp-content/themes/community };f'
alias linkexp='f() { ln -s ~/a8c/repos/experiments ~/a8c/Local\ sites/$1/app/public/wp-content/themes/theme-experiments };f'
alias linkgb='f() { ln -s ~/a8c/repos/gutenberg ~/a8c/Local\ sites/$1/app/public/wp-content/plugins/gutenberg };f'

# Add Visual Studio Code (code)
export PATH="/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$PATH"

# nvm (installed with brew)
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"

# pyenv
if command -v pyenv >/dev/null; then
  export PYENV_ROOT="$HOME/.pyenv"
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi

# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# Woocommerce aliases
function install-globals {
  nvm install
  nvm use
  npm install -g pnpm@latest
  npm install -g @wordpress/env@latest
}

function reset-lock-file {
  git reset HEAD pnpm-lock.yaml
  git checkout -- pnpm-lock.yaml
}

function wc-build {
  # cd ~/a8c/repos/woocommerce
  install-globals
  nvm use
  pnpm install --frozen-lockfile
  pnpm run build
  pnpm --filter='@woocommerce/plugin-woocommerce' build
  reset-lock-file
}

function wc-fresh-install {
  # cd ~/a8c/repos/woocommerce
  git reset --hard
  git clean -fdx
  rimraf node_modules
  wc-build
}

function wc-watch {
  wc-build
  pnpm --filter='@woocommerce/plugin-woocommerce' watch:build
}

export PATH="$HOME/.local/bin:$PATH"
